# Day 2 - Numpy and Pandas
Materi hari ini akan kita pelajari tentang library numpy dan pandas. Untuk itu kita perlu lakukan instalasi kedua library tersebut dengan command: pip install numpy dan pip install pandas

In [1]:
import numpy as np
import pandas as pd
import random as rd

## Numpy
Numerical Python

In [2]:
# membuat array dari list
list1 = [rd.choice(range(10,100)) for i in range(20)]

In [3]:
print(list1)

[64, 59, 77, 59, 83, 41, 62, 76, 30, 64, 95, 22, 36, 92, 29, 55, 35, 22, 40, 21]

In [4]:
# convert ke array
data1 = np.array(list1)

In [5]:
data1

array([64, 59, 77, 59, 83, 41, 62, 76, 30, 64, 95, 22, 36, 92, 29, 55, 35,
       22, 40, 21])

## Fungsi statistik

In [6]:
data1.sum()

1062

In [7]:
data1.mean()

53.1

In [8]:
print(data1.min())
print(data1.max())
print(data1.std())

21
95
23.093072554339752

## Pandas
Series dan DataFrame

Dataset download https://1drv.ms/u/s!AjPEEBS-0ywVg4QAaD2vVbZB0mDRrA?e=XFrptV

## Series
Series merupakan struktur data dasar dalam Pandas yang diibaratkan sebagai array satu dimensi seperti halnya yang ada pada numpy array, hanya bedanya mempunyai index dan kita dapat mengontrol index dari setiap elemen tersebut.

In [9]:
data2 = pd.Series(list1)

In [10]:
data2

0     64
1     59
2     77
3     59
4     83
5     41
6     62
7     76
8     30
9     64
10    95
11    22
12    36
13    92
14    29
15    55
16    35
17    22
18    40
19    21
dtype: int64

In [11]:
data2[5]

41

In [12]:
data2[5:11]

5     41
6     62
7     76
8     30
9     64
10    95
dtype: int64

In [13]:
data2.iloc[5]

41

In [14]:
data2.iloc[5:11]

5     41
6     62
7     76
8     30
9     64
10    95
dtype: int64

In [15]:
list2 = [20, 35, 53, 42, 61]

In [16]:
data3 = pd.Series(list2, index=['a','b','c','d','e'])

In [17]:
data3

a    20
b    35
c    53
d    42
e    61
dtype: int64

In [18]:
data3['a']

20

In [19]:
data3.loc['b']

35

In [20]:
data3.loc['b':'e']

b    35
c    53
d    42
e    61
dtype: int64

## Read File

In [21]:
data4 = pd.read_csv('../Data/titanic.csv')

In [22]:
dt_name = pd.Series(data4['Name'])

In [23]:
dt_name.head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [24]:
dt_name.iloc[500: 511]

500                                 Calic, Mr. Petar
501                              Canavan, Miss. Mary
502                   O'Sullivan, Miss. Bridget Mary
503                   Laitinen, Miss. Kristina Sofia
504                            Maioni, Miss. Roberta
505       Penasco y Castellana, Mr. Victor de Satode
506    Quick, Mrs. Frederick Charles (Jane Richards)
507    Bradley, Mr. George ("George Arthur Brayton")
508                         Olsen, Mr. Henry Margido
509                                   Lang, Mr. Fang
510                         Daly, Mr. Eugene Patrick
Name: Name, dtype: object

## DataFrame
DataFrame adalah struktur data 2 dimensi yang berbentuk tabular (mempunyai baris dan kolom). Setiap kolom pada Data Frame merupakan objek dari Series, dan baris terdiri dari elemen yang ada pada Series.

In [25]:
# create dataframe dari dict
dict_staff = {
    'div':[rd.choice(['backend','frontend','ui/ux']) for i in range(50)],
    'jk':[rd.choice(['L','P']) for i in range(50)],
    'age':[rd.choice(range(23,37)) for i in range(50)],
    'rating':[rd.uniform(0.0, 10.0) for i in range(50)],
    'branch':[rd.choice(['Jkt','Bdg','Yk','Sby','Dps']) for i in range(50)]
}

In [26]:
df_staff = pd.DataFrame(dict_staff)

In [27]:
df_staff.head()

       div jk  age    rating branch
0  backend  P   26  0.890258    Dps
1    ui/ux  P   28  7.554872    Sby
2    ui/ux  L   25  7.893103    Sby
3    ui/ux  P   28  2.248737    Sby
4    ui/ux  P   30  0.390445    Bdg

In [28]:
df_staff.describe()

             age     rating
count  50.000000  50.000000
mean   29.520000   5.145312
std     3.923971   3.022053
min    23.000000   0.012777
25%    27.000000   2.300696
50%    29.000000   5.614242
75%    33.000000   7.748507
max    36.000000   9.658558

In [29]:
df_staff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
div       50 non-null object
jk        50 non-null object
age       50 non-null int64
rating    50 non-null float64
branch    50 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.0+ KB

In [30]:
df_staff.columns

Index(['div', 'jk', 'age', 'rating', 'branch'], dtype='object')

In [31]:
df_staff.shape

(50, 5)

## Slicing Data

In [32]:
df_staff.loc[20:25, 'jk':'age']

   jk  age
20  L   27
21  P   35
22  L   24
23  L   23
24  L   24
25  P   29

In [33]:
df_staff.iloc[20:26, 1:3] # inclusive : exclusive

   jk  age
20  L   27
21  P   35
22  L   24
23  L   23
24  L   24
25  P   29

In [34]:
df_staff.loc[30:40]

         div jk  age    rating branch
30     ui/ux  P   28  8.903526    Bdg
31   backend  P   33  7.748258    Bdg
32     ui/ux  L   34  5.505106    Sby
33     ui/ux  P   27  5.964371     Yk
34  frontend  L   34  0.012777    Bdg
35   backend  P   29  8.914327    Jkt
36     ui/ux  L   35  0.915109     Yk
37   backend  L   29  8.102761    Dps
38     ui/ux  P   27  1.363403    Sby
39     ui/ux  L   28  8.533933    Jkt
40  frontend  P   30  6.580917    Jkt

## Filtering

In [35]:
df_staff[df_staff.jk == 'P']

         div jk  age    rating branch
0    backend  P   26  0.890258    Dps
1      ui/ux  P   28  7.554872    Sby
3      ui/ux  P   28  2.248737    Sby
4      ui/ux  P   30  0.390445    Bdg
5      ui/ux  P   35  2.868223    Bdg
6    backend  P   28  2.555315    Jkt
7      ui/ux  P   27  5.184250    Sby
8    backend  P   35  6.692593    Dps
9      ui/ux  P   24  2.456574    Dps
10  frontend  P   36  5.723378    Bdg
12   backend  P   32  1.878577     Yk
16     ui/ux  P   32  0.912190    Jkt
17     ui/ux  P   27  4.941482    Sby
19     ui/ux  P   24  2.142163    Dps
21  frontend  P   35  7.748591    Bdg
25  frontend  P   29  4.936670    Jkt
26     ui/ux  P   26  0.505695    Jkt
28  frontend  P   28  7.746442    Dps
30     ui/ux  P   28  8.903526    Bdg
31   backend  P   33  7.748258    Bdg
33     ui/ux  P   27  5.964371     Yk
35   backend  P   29  8.914327    Jkt
38     ui/ux  P   27  1.363403    Sby
40  frontend  P   30  6.580917    Jkt
41   backend  P   26  4.634010    Bdg
44  frontend  P   33  0.758612    Sby
46   backend  P   33  6.639949    Dps
48   backend  P   25  9.238841     Yk
49     ui/ux  P   25  5.957955    Sby

In [36]:
staff_pr = df_staff.jk == 'P'
staff_yk = df_staff.branch == 'Yk'

In [37]:
df_staff[staff_pr & staff_yk]

        div jk  age    rating branch
12  backend  P   32  1.878577     Yk
33    ui/ux  P   27  5.964371     Yk
48  backend  P   25  9.238841     Yk

In [38]:
df_staff.jk.value_counts()

P    29
L    21
Name: jk, dtype: int64

In [39]:
df_staff[staff_yk].count()

div       6
jk        6
age       6
rating    6
branch    6
dtype: int64

## Map & Apply

In [40]:
df_staff.head()

       div jk  age    rating branch
0  backend  P   26  0.890258    Dps
1    ui/ux  P   28  7.554872    Sby
2    ui/ux  L   25  7.893103    Sby
3    ui/ux  P   28  2.248737    Sby
4    ui/ux  P   30  0.390445    Bdg

In [41]:
df_staff['jen_kel'] = df_staff.jk.map({'L':'Laki-laki','P':'Perempuan'})

In [42]:
df_staff.head()

       div jk  age    rating branch    jen_kel
0  backend  P   26  0.890258    Dps  Perempuan
1    ui/ux  P   28  7.554872    Sby  Perempuan
2    ui/ux  L   25  7.893103    Sby  Laki-laki
3    ui/ux  P   28  2.248737    Sby  Perempuan
4    ui/ux  P   30  0.390445    Bdg  Perempuan

In [43]:
def rating_up(x):
    return x * 10

In [44]:
df_staff['rating_up'] = df_staff.rating.apply(rating_up)

In [45]:
df_staff.head()

       div jk  age    rating branch    jen_kel  rating_up
0  backend  P   26  0.890258    Dps  Perempuan   8.902584
1    ui/ux  P   28  7.554872    Sby  Perempuan  75.548722
2    ui/ux  L   25  7.893103    Sby  Laki-laki  78.931031
3    ui/ux  P   28  2.248737    Sby  Perempuan  22.487371
4    ui/ux  P   30  0.390445    Bdg  Perempuan   3.904447

## Scaling

In [46]:
# fungsi normalisasi
def normalisasi(x):
    a = x - x.min()
    b = x.max() - x.min()
    return a/b

In [47]:
df_staff['age_norm'] = df_staff[['age']].apply(normalisasi)

In [48]:
df_staff.head()

       div jk  age    rating branch    jen_kel  rating_up  age_norm
0  backend  P   26  0.890258    Dps  Perempuan   8.902584  0.230769
1    ui/ux  P   28  7.554872    Sby  Perempuan  75.548722  0.384615
2    ui/ux  L   25  7.893103    Sby  Laki-laki  78.931031  0.153846
3    ui/ux  P   28  2.248737    Sby  Perempuan  22.487371  0.384615
4    ui/ux  P   30  0.390445    Bdg  Perempuan   3.904447  0.538462

## Sorting

In [49]:
df_staff.sort_values('rating', ascending=False).head()

         div jk  age    rating branch    jen_kel  rating_up  age_norm
47  frontend  L   29  9.658558    Bdg  Laki-laki  96.585582  0.461538
13   backend  L   31  9.462536    Bdg  Laki-laki  94.625359  0.615385
27   backend  L   33  9.326465     Yk  Laki-laki  93.264652  0.769231
48   backend  P   25  9.238841     Yk  Perempuan  92.388413  0.153846
35   backend  P   29  8.914327    Jkt  Perempuan  89.143267  0.461538

In [50]:
df_staff.sort_values(['age','rating'], ascending=[True, False])

         div jk  age    rating branch    jen_kel  rating_up  age_norm
23  frontend  L   23  8.420838    Sby  Laki-laki  84.208378  0.000000
22     ui/ux  L   24  7.148563    Jkt  Laki-laki  71.485630  0.076923
15   backend  L   24  3.743920    Dps  Laki-laki  37.439200  0.076923
9      ui/ux  P   24  2.456574    Dps  Perempuan  24.565739  0.076923
19     ui/ux  P   24  2.142163    Dps  Perempuan  21.421633  0.076923
24  frontend  L   24  2.048324    Dps  Laki-laki  20.483243  0.076923
48   backend  P   25  9.238841     Yk  Perempuan  92.388413  0.153846
2      ui/ux  L   25  7.893103    Sby  Laki-laki  78.931031  0.153846
49     ui/ux  P   25  5.957955    Sby  Perempuan  59.579547  0.153846
41   backend  P   26  4.634010    Bdg  Perempuan  46.340096  0.230769
0    backend  P   26  0.890258    Dps  Perempuan   8.902584  0.230769
26     ui/ux  P   26  0.505695    Jkt  Perempuan   5.056946  0.230769
33     ui/ux  P   27  5.964371     Yk  Perempuan  59.643707  0.307692
7      ui/ux  P   27  5.184250    Sby  Perempuan  51.842505  0.307692
17     ui/ux  P   27  4.941482    Sby  Perempuan  49.414815  0.307692
20     ui/ux  L   27  3.246752     Yk  Laki-laki  32.467525  0.307692
38     ui/ux  P   27  1.363403    Sby  Perempuan  13.634028  0.307692
30     ui/ux  P   28  8.903526    Bdg  Perempuan  89.035261  0.384615
18     ui/ux  L   28  8.681329    Dps  Laki-laki  86.813294  0.384615
39     ui/ux  L   28  8.533933    Jkt  Laki-laki  85.339325  0.384615
28  frontend  P   28  7.746442    Dps  Perempuan  77.464424  0.384615
1      ui/ux  P   28  7.554872    Sby  Perempuan  75.548722  0.384615
6    backend  P   28  2.555315    Jkt  Perempuan  25.553145  0.384615
3      ui/ux  P   28  2.248737    Sby  Perempuan  22.487371  0.384615
47  frontend  L   29  9.658558    Bdg  Laki-laki  96.585582  0.461538
35   backend  P   29  8.914327    Jkt  Perempuan  89.143267  0.461538
37   backend  L   29  8.102761    Dps  Laki-laki  81.027611  0.461538
29  frontend  L   29  6.143333    Bdg  Laki-laki  61.433326  0.461538
25  frontend  P   29  4.936670    Jkt  Perempuan  49.366697  0.461538
40  frontend  P   30  6.580917    Jkt  Perempuan  65.809168  0.538462
4      ui/ux  P   30  0.390445    Bdg  Perempuan   3.904447  0.538462
13   backend  L   31  9.462536    Bdg  Laki-laki  94.625359  0.615385
42     ui/ux  L   31  4.486764    Sby  Laki-laki  44.867638  0.615385
12   backend  P   32  1.878577     Yk  Perempuan  18.785769  0.692308
16     ui/ux  P   32  0.912190    Jkt  Perempuan   9.121901  0.692308
27   backend  L   33  9.326465     Yk  Laki-laki  93.264652  0.769231
31   backend  P   33  7.748258    Bdg  Perempuan  77.482582  0.769231
46   backend  P   33  6.639949    Dps  Perempuan  66.399493  0.769231
44  frontend  P   33  0.758612    Sby  Perempuan   7.586116  0.769231
32     ui/ux  L   34  5.505106    Sby  Laki-laki  55.051060  0.846154
34  frontend  L   34  0.012777    Bdg  Laki-laki   0.127767  0.846154
21  frontend  P   35  7.748591    Bdg  Perempuan  77.485905  0.923077
8    backend  P   35  6.692593    Dps  Perempuan  66.925926  0.923077
11     ui/ux  L   35  4.252542    Dps  Laki-laki  42.525423  0.923077
5      ui/ux  P   35  2.868223    Bdg  Perempuan  28.682233  0.923077
36     ui/ux  L   35  0.915109     Yk  Laki-laki   9.151088  0.923077
14  frontend  L   35  0.708242    Dps  Laki-laki   7.082423  0.923077
43   backend  L   36  8.698747    Dps  Laki-laki  86.987469  1.000000
45   backend  L   36  6.195280    Sby  Laki-laki  61.952798  1.000000
10  frontend  P   36  5.723378    Bdg  Perempuan  57.233783  1.000000

## Pivot Tabel

In [51]:
df_staff.pivot_table(index='jk', columns='branch', values='rating', aggfunc='mean')

branch       Bdg       Dps       Jkt       Sby        Yk
jk
L       6.319301  5.176552  7.841248  6.500218  4.496109
P       5.430919  4.427997  4.067519  4.001330  5.693930

## Grouping

In [52]:
df_staff.groupby('div').mean()

                age    rating  rating_up  age_norm
div
backend   30.400000  6.314789  63.147891  0.569231
frontend  30.416667  5.040557  50.405568  0.570513
ui/ux     28.478261  4.437265  44.372646  0.421405

In [54]:
df_staff.head()

       div jk  age    rating branch    jen_kel  rating_up  age_norm
0  backend  P   26  0.890258    Dps  Perempuan   8.902584  0.230769
1    ui/ux  P   28  7.554872    Sby  Perempuan  75.548722  0.384615
2    ui/ux  L   25  7.893103    Sby  Laki-laki  78.931031  0.153846
3    ui/ux  P   28  2.248737    Sby  Perempuan  22.487371  0.384615
4    ui/ux  P   30  0.390445    Bdg  Perempuan   3.904447  0.538462

In [55]:
df_staff.drop(columns='rating_up', inplace=True)

In [56]:
df_staff.head()

       div jk  age    rating branch    jen_kel  age_norm
0  backend  P   26  0.890258    Dps  Perempuan  0.230769
1    ui/ux  P   28  7.554872    Sby  Perempuan  0.384615
2    ui/ux  L   25  7.893103    Sby  Laki-laki  0.153846
3    ui/ux  P   28  2.248737    Sby  Perempuan  0.384615
4    ui/ux  P   30  0.390445    Bdg  Perempuan  0.538462

## Save File

In [67]:
df_staff.to_csv('../Data/staff.csv')

## Data Sereal

In [57]:
df_cereal = pd.read_csv('../Data/cereal.csv')

In [58]:
df_cereal.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.0,0.75,34.384843

In [59]:
df_cereal.shape

(77, 16)

In [60]:
df_cereal.isna().sum()

name        0
mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       1
sugars      1
potass      2
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [61]:
# hapus data kosong
df_cereal.dropna

<bound method DataFrame.dropna of                                       name mfr type  calories  protein  fat  \
0                                100% Bran   N    C        70        4    1
1                        100% Natural Bran   Q    C       120        3    5
2                                 All-Bran   K    C        70        4    1
3                All-Bran with Extra Fiber   K    C        50        4    0
4                           Almond Delight   R    C       110        2    2
5                  Apple Cinnamon Cheerios   G    C       110        2    2
6                              Apple Jacks   K    C       110        2    0
7                                  Basic 4   G    C       130        3    2
8                                Bran Chex   R    C        90        2    1
9                              Bran Flakes   P    C        90        3    0
10                            Cap'n'Crunch   Q    C       120        1    2
11                                Cheerios   G    C       110        6    2
12                   Cinnamon Toast Crunch   G    C       120        1    3
13                                Clusters   G    C       110        3    2
14                             Cocoa Puffs   G    C       110        1    1
15                               Corn Chex   R    C       110        2    0
16                             Corn Flakes   K    C       100        2    0
17                               Corn Pops   K    C       110        1    0
18                           Count Chocula   G    C       110        1    1
19                      Cracklin' Oat Bran   K    C       110        3    3
20                  Cream of Wheat (Quick)   N    H       100        3    0
21                                 Crispix   K    C       110        2    0
22                  Crispy Wheat & Raisins   G    C       100        2    1
23                             Double Chex   R    C       100        2    0
24                             Froot Loops   K    C       110        2    1
25                          Frosted Flakes   K    C       110        1    0
26                     Frosted Mini-Wheats   K    C       100        3    0
27  Fruit & Fibre Dates; Walnuts; and Oats   P    C       120        3    2
28                           Fruitful Bran   K    C       120        3    0
29                          Fruity Pebbles   P    C       110        1    1
..                                     ...  ..  ...       ...      ...  ...
47                    Multi-Grain Cheerios   G    C       100        2    1
48                        Nut&Honey Crunch   K    C       120        2    1
49               Nutri-Grain Almond-Raisin   K    C       140        3    2
50                       Nutri-grain Wheat   K    C        90        3    0
51                    Oatmeal Raisin Crisp   G    C       130        3    2
52                   Post Nat. Raisin Bran   P    C       120        3    1
53                              Product 19   K    C       100        3    0
54                             Puffed Rice   Q    C        50        1    0
55                            Puffed Wheat   Q    C        50        2    0
56                      Quaker Oat Squares   Q    C       100        4    1
57                          Quaker Oatmeal   Q    H       100        5    2
58                             Raisin Bran   K    C       120        3    1
59                         Raisin Nut Bran   G    C       100        3    2
60                          Raisin Squares   K    C        90        2    0
61                               Rice Chex   R    C       110        1    0
62                           Rice Krispies   K    C       110        2    0
63                          Shredded Wheat   N    C        80        2    0
64                  Shredded Wheat 'n'Bran   N    C        90        3    0
65               Shredded Wheat spoon size   N    C        90        3    0
66                                  Smacks   K    C       110        2    1
67                               Special K   K    C       110        6    0
68                 Strawberry Fruit Wheats   N    C        90        2    0
69                       Total Corn Flakes   G    C       110        2    1
70                       Total Raisin Bran   G    C       140        3    1
71                       Total Whole Grain   G    C       100        3    1
72                                 Triples   G    C       110        2    1
73                                    Trix   G    C       110        1    1
74                              Wheat Chex   R    C       100        3    1
75                                Wheaties   G    C       100        3    1
76                     Wheaties Honey Gold   G    C       110        2    1

    sodium  fiber  carbo  sugars  potass vitamins  shelf  weight  cups  \
0      130   10.0    5.0     6.0   280.0   FDA_25      3    1.00  0.33
1       15    2.0    8.0     8.0   135.0    FDA_0      3    1.00  1.00
2      260    9.0    7.0     5.0   320.0   FDA_25      3    1.00  0.33
3      140   14.0    8.0     0.0   330.0   FDA_25      3    1.00  0.50
4      200    1.0   14.0     8.0     NaN   FDA_25      3    1.00  0.75
5      180    1.5   10.5    10.0    70.0   FDA_25      1    1.00  0.75
6      125    1.0   11.0    14.0    30.0   FDA_25      2    1.00  1.00
7      210    2.0   18.0     8.0   100.0   FDA_25      3    1.33  0.75
8      200    4.0   15.0     6.0   125.0   FDA_25      1    1.00  0.67
9      210    5.0   13.0     5.0   190.0   FDA_25      3    1.00  0.67
10     220    0.0   12.0    12.0    35.0   FDA_25      2    1.00  0.75
11     290    2.0   17.0     1.0   105.0   FDA_25      1    1.00  1.25
12     210    0.0   13.0     9.0    45.0   FDA_25      2    1.00  0.75
13     140    2.0   13.0     7.0   105.0   FDA_25      3    1.00  0.50
14     180    0.0   12.0    13.0    55.0   FDA_25      2    1.00  1.00
15     280    0.0   22.0     3.0    25.0   FDA_25      1    1.00  1.00
16     290    1.0   21.0     2.0    35.0   FDA_25      1    1.00  1.00
17      90    1.0   13.0    12.0    20.0   FDA_25      2    1.00  1.00
18     180    0.0   12.0    13.0    65.0   FDA_25      2    1.00  1.00
19     140    4.0   10.0     7.0   160.0   FDA_25      3    1.00  0.50
20      80    1.0   21.0     0.0     NaN    FDA_0      2    1.00  1.00
21     220    1.0   21.0     3.0    30.0   FDA_25      3    1.00  1.00
22     140    2.0   11.0    10.0   120.0   FDA_25      3    1.00  0.75
23     190    1.0   18.0     5.0    80.0   FDA_25      3    1.00  0.75
24     125    1.0   11.0    13.0    30.0   FDA_25      2    1.00  1.00
25     200    1.0   14.0    11.0    25.0   FDA_25      1    1.00  0.75
26       0    3.0   14.0     7.0   100.0   FDA_25      2    1.00  0.80
27     160    5.0   12.0    10.0   200.0   FDA_25      3    1.25  0.67
28     240    5.0   14.0    12.0   190.0   FDA_25      3    1.33  0.67
29     135    0.0   13.0    12.0    25.0   FDA_25      2    1.00  0.75
..     ...    ...    ...     ...     ...      ...    ...     ...   ...
47     220    2.0   15.0     6.0    90.0   FDA_25      1    1.00  1.00
48     190    0.0   15.0     9.0    40.0   FDA_25      2    1.00  0.67
49     220    3.0   21.0     7.0   130.0   FDA_25      3    1.33  0.67
50     170    3.0   18.0     2.0    90.0   FDA_25      3    1.00  1.00
51     170    1.5   13.5    10.0   120.0   FDA_25      3    1.25  0.50
52     200    6.0   11.0    14.0   260.0   FDA_25      3    1.33  0.67
53     320    1.0   20.0     3.0    45.0  FDA_100      3    1.00  1.00
54       0    0.0   13.0     0.0    15.0    FDA_0      3    0.50  1.00
55       0    1.0   10.0     0.0    50.0    FDA_0      3    0.50  1.00
56     135    2.0   14.0     6.0   110.0   FDA_25      3    1.00  0.50
57       0    2.7    NaN     NaN   110.0    FDA_0      1    1.00  0.67
58     210    5.0   14.0    12.0   240.0   FDA_25      2    1.33  0.75
59     140    2.5   10.5     8.0   140.0   FDA_25      3    1.00  0.50
60       0    2.0   15.0     6.0   110.0   FDA_25      3    1.00  0.50
61     240    0.0   23.0     2.0    30.0   FDA_25      1    1.00  1.13
62     290    0.0   22.0     3.0    35.0   FDA_25      1    1.00  1.00
63       0    3.0   16.0     0.0    95.0    FDA_0      1    0.83  1.00
64       0    4.0   19.0     0.0   140.0    FDA_0      1    1.00  0.67
65       0    3.0   20.0     0.0   120.0    FDA_0      1    1.00  0.67
66      70    1.0    9.0    15.0    40.0   FDA_25      2    1.00  0.75
67     230    1.0   16.0     3.0    55.0   FDA_25      1    1.00  1.00
68      15    3.0   15.0     5.0    90.0   FDA_25      2    1.00  1.00
69     200    0.0   21.0     3.0    35.0  FDA_100      3    1.00  1.00
70     190    4.0   15.0    14.0   230.0  FDA_100      3    1.50  1.00
71     200    3.0   16.0     3.0   110.0  FDA_100      3    1.00  1.00
72     250    0.0   21.0     3.0    60.0   FDA_25      3    1.00  0.75
73     140    0.0   13.0    12.0    25.0   FDA_25      2    1.00  1.00
74     230    3.0   17.0     3.0   115.0   FDA_25      1    1.00  0.67
75     200    3.0   17.0     3.0   110.0   FDA_25      1    1.00  1.00
76     200    1.0   16.0     8.0    60.0   FDA_25      1    1.00  0.75

       rating
0   68.402973
1   33.983679
2   59.425505
3   93.704912
4   34.384843
5   29.509541
6   33.174094
7   37.038562
8   49.120253
9   53.313813
10  18.042851
11  50.764999
12  19.823573
13  40.400208
14  22.736446
15  41.445019
16  45.863324
17  35.782791
18  22.396513
19  40.448772
20  64.533816
21  46.895644
22  36.176196
23  44.330856
24  32.207582
25  31.435973
26  58.345141
27  40.917047
28  41.015492
29  28.025765
..        ...
47  40.105965
48  29.924285
49  40.692320
50  59.642837
51  30.450843
52  37.840594
53  41.503540
54  60.756112
55  63.005645
56  49.511874
57  50.828392
58  39.259197
59  39.703400
60  55.333142
61  41.998933
62  40.560159
63  68.235885
64  74.472949
65  72.801787
66  31.230054
67  53.131324
68  59.363993
69  38.839746
70  28.592785
71  46.658844
72  39.106174
73  27.753301
74  49.787445
75  51.592193
76  36.187559

[77 rows x 16 columns]>

In [62]:
# mengisi nilai
df_cereal.fillna('--empty--')

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5,6,280,FDA_25,3,1.00,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8,8,135,FDA_0,3,1.00,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7,5,320,FDA_25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8,0,330,FDA_25,3,1.00,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14,8,--empty--,FDA_25,3,1.00,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,FDA_25,1,1.00,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11,14,30,FDA_25,2,1.00,1.00,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18,8,100,FDA_25,3,1.33,0.75,37.038562
8,Bran Chex,R,C,90,2,1,200,4.0,15,6,125,FDA_25,1,1.00,0.67,49.120253
9,Bran Flakes,P,C,90,3,0,210,5.0,13,5,190,FDA_25,3,1.00,0.67,53.313813
10,Cap'n'Crunch,Q,C,120,1,2,220,0.0,12,12,35,FDA_25,2,1.00,0.75,18.042851
11,Cheerios,G,C,110,6,2,290,2.0,17,1,105,FDA_25,1,1.00,1.25,50.764999
12,Cinnamon Toast Crunch,G,C,120,1,3,210,0.0,13,9,45,FDA_25,2,1.00,0.75,19.823573
13,Clusters,G,C,110,3,2,140,2.0,13,7,105,FDA_25,3,1.00,0.50,40.400208
14,Cocoa Puffs,G,C,110,1,1,180,0.0,12,13,55,FDA_25,2,1.00,1.00,22.736446
15,Corn Chex,R,C,110,2,0,280,0.0,22,3,25,FDA_25,1,1.00,1.00,41.445019
16,Corn Flakes,K,C,100,2,0,290,1.0,21,2,35,FDA_25,1,1.00,1.00,45.863324
17,Corn Pops,K,C,110,1,0,90,1.0,13,12,20,FDA_25,2,1.00,1.00,35.782791
18,Count Chocula,G,C,110,1,1,180,0.0,12,13,65,FDA_25,2,1.00,1.00,22.396513
19,Cracklin' Oat Bran,K,C,110,3,3,140,4.0,10,7,160,FDA_25,3,1.00,0.50,40.448772
20,Cream of Wheat (Quick),N,H,100,3,0,80,1.0,21,0,--empty--,FDA_0,2,1.00,1.00,64.533816
21,Crispix,K,C,110,2,0,220,1.0,21,3,30,FDA_25,3,1.00,1.00,46.895644
22,Crispy Wheat & Raisins,G,C,100,2,1,140,2.0,11,10,120,FDA_25,3,1.00,0.75,36.176196
23,Double Chex,R,C,100,2,0,190,1.0,18,5,80,FDA_25,3,1.00,0.75,44.330856
24,Froot Loops,K,C,110,2,1,125,1.0,11,13,30,FDA_25,2,1.00,1.00,32.207582
25,Frosted Flakes,K,C,110,1,0,200,1.0,14,11,25,FDA_25,1,1.00,0.75,31.435973
26,Frosted Mini-Wheats,K,C,100,3,0,0,3.0,14,7,100,FDA_25,2,1.00,0.80,58.345141
27,Fruit & Fibre Dates; Walnuts; and Oats,P,C,120,3,2,160,5.0,12,10,200,FDA_25,3,1.25,0.67,40.917047
28,Fruitful Bran,K,C,120,3,0,240,5.0,14,12,190,FDA_25,3,1.33,0.67,41.015492
29,Fruity Pebbles,P,C,110,1,1,135,0.0,13,12,25,FDA_25,2,1.00,0.75,28.025765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,Multi-Grain Cheerios,G,C,100,2,1,220,2.0,15,6,90,FDA_25,1,1.00,1.00,40.105965
48,Nut&Honey Crunch,K,C,120,2,1,190,0.0,15,9,40,FDA_25,2,1.00,0.67,29.924285
49,Nutri-Grain Almond-Raisin,K,C,140,3,2,220,3.0,21,7,130,FDA_25,3,1.33,0.67,40.692320
50,Nutri-grain Wheat,K,C,90,3,0,170,3.0,18,2,90,FDA_25,3,1.00,1.00,59.642837
51,Oatmeal Raisin Crisp,G,C,130,3,2,170,1.5,13.5,10,120,FDA_25,3,1.25,0.50,30.450843
52,Post Nat. Raisin Bran,P,C,120,3,1,200,6.0,11,14,260,FDA_25,3,1.33,0.67,37.840594
53,Product 19,K,C,100,3,0,320,1.0,20,3,45,FDA_100,3,1.00,1.00,41.503540
54,Puffed Rice,Q,C,50,1,0,0,0.0,13,0,15,FDA_0,3,0.50,1.00,60.756112
55,Puffed Wheat,Q,C,50,2,0,0,1.0,10,0,50,FDA_0,3,0.50,1.00,63.005645
56,Quaker Oat Squares,Q,C,100,4,1,135,2.0,14,6,110,FDA_25,3,1.00,0.50,49.511874
57,Quaker Oatmeal,Q,H,100,5,2,0,2.7,--empty--,--empty--,110,FDA_0,1,1.00,0.67,50.828392
58,Raisin Bran,K,C,120,3,1,210,5.0,14,12,240,FDA_25,2,1.33,0.75,39.259197
59,Raisin Nut Bran,G,C,100,3,2,140,2.5,10.5,8,140,FDA_25,3,1.00,0.50,39.703400
60,Raisin Squares,K,C,90,2,0,0,2.0,15,6,110,FDA_25,3,1.00,0.50,55.333142
61,Rice Chex,R,C,110,1,0,240,0.0,23,2,30,FDA_25,1,1.00,1.13,41.998933
62,Rice Krispies,K,C,110,2,0,290,0.0,22,3,35,FDA_25,1,1.00,1.00,40.560159
63,Shredded Wheat,N,C,80,2,0,0,3.0,16,0,95,FDA_0,1,0.83,1.00,68.235885
64,Shredded Wheat 'n'Bran,N,C,90,3,0,0,4.0,19,0,140,FDA_0,1,1.00,0.67,74.472949
65,Shredded Wheat spoon size,N,C,90,3,0,0,3.0,20,0,120,FDA_0,1,1.00,0.67,72.801787
66,Smacks,K,C,110,2,1,70,1.0,9,15,40,FDA_25,2,1.00,0.75,31.230054
67,Special K,K,C,110,6,0,230,1.0,16,3,55,FDA_25,1,1.00,1.00,53.131324
68,Strawberry Fruit Wheats,N,C,90,2,0,15,3.0,15,5,90,FDA_25,2,1.00,1.00,59.363993
69,Total Corn Flakes,G,C,110,2,1,200,0.0,21,3,35,FDA_100,3,1.00,1.00,38.839746
70,Total Raisin Bran,G,C,140,3,1,190,4.0,15,14,230,FDA_100,3,1.50,1.00,28.592785
71,Total Whole Grain,G,C,100,3,1,200,3.0,16,3,110,FDA_100,3,1.00,1.00,46.658844
72,Triples,G,C,110,2,1,250,0.0,21,3,60,FDA_25,3,1.00,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13,12,25,FDA_25,2,1.00,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17,3,115,FDA_25,1,1.00,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17,3,110,FDA_25,1,1.00,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16,8,60,FDA_25,1,1.00,0.75,36.187559

In [63]:
filler = {'carbo':'--carbo--', 'sugars':'--sugars--', 'potass':'--potass--'}
df_cereal.fillna(filler)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5,6,280,FDA_25,3,1.00,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8,8,135,FDA_0,3,1.00,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7,5,320,FDA_25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8,0,330,FDA_25,3,1.00,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14,8,--potass--,FDA_25,3,1.00,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,FDA_25,1,1.00,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11,14,30,FDA_25,2,1.00,1.00,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18,8,100,FDA_25,3,1.33,0.75,37.038562
8,Bran Chex,R,C,90,2,1,200,4.0,15,6,125,FDA_25,1,1.00,0.67,49.120253
9,Bran Flakes,P,C,90,3,0,210,5.0,13,5,190,FDA_25,3,1.00,0.67,53.313813
10,Cap'n'Crunch,Q,C,120,1,2,220,0.0,12,12,35,FDA_25,2,1.00,0.75,18.042851
11,Cheerios,G,C,110,6,2,290,2.0,17,1,105,FDA_25,1,1.00,1.25,50.764999
12,Cinnamon Toast Crunch,G,C,120,1,3,210,0.0,13,9,45,FDA_25,2,1.00,0.75,19.823573
13,Clusters,G,C,110,3,2,140,2.0,13,7,105,FDA_25,3,1.00,0.50,40.400208
14,Cocoa Puffs,G,C,110,1,1,180,0.0,12,13,55,FDA_25,2,1.00,1.00,22.736446
15,Corn Chex,R,C,110,2,0,280,0.0,22,3,25,FDA_25,1,1.00,1.00,41.445019
16,Corn Flakes,K,C,100,2,0,290,1.0,21,2,35,FDA_25,1,1.00,1.00,45.863324
17,Corn Pops,K,C,110,1,0,90,1.0,13,12,20,FDA_25,2,1.00,1.00,35.782791
18,Count Chocula,G,C,110,1,1,180,0.0,12,13,65,FDA_25,2,1.00,1.00,22.396513
19,Cracklin' Oat Bran,K,C,110,3,3,140,4.0,10,7,160,FDA_25,3,1.00,0.50,40.448772
20,Cream of Wheat (Quick),N,H,100,3,0,80,1.0,21,0,--potass--,FDA_0,2,1.00,1.00,64.533816
21,Crispix,K,C,110,2,0,220,1.0,21,3,30,FDA_25,3,1.00,1.00,46.895644
22,Crispy Wheat & Raisins,G,C,100,2,1,140,2.0,11,10,120,FDA_25,3,1.00,0.75,36.176196
23,Double Chex,R,C,100,2,0,190,1.0,18,5,80,FDA_25,3,1.00,0.75,44.330856
24,Froot Loops,K,C,110,2,1,125,1.0,11,13,30,FDA_25,2,1.00,1.00,32.207582
25,Frosted Flakes,K,C,110,1,0,200,1.0,14,11,25,FDA_25,1,1.00,0.75,31.435973
26,Frosted Mini-Wheats,K,C,100,3,0,0,3.0,14,7,100,FDA_25,2,1.00,0.80,58.345141
27,Fruit & Fibre Dates; Walnuts; and Oats,P,C,120,3,2,160,5.0,12,10,200,FDA_25,3,1.25,0.67,40.917047
28,Fruitful Bran,K,C,120,3,0,240,5.0,14,12,190,FDA_25,3,1.33,0.67,41.015492
29,Fruity Pebbles,P,C,110,1,1,135,0.0,13,12,25,FDA_25,2,1.00,0.75,28.025765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,Multi-Grain Cheerios,G,C,100,2,1,220,2.0,15,6,90,FDA_25,1,1.00,1.00,40.105965
48,Nut&Honey Crunch,K,C,120,2,1,190,0.0,15,9,40,FDA_25,2,1.00,0.67,29.924285
49,Nutri-Grain Almond-Raisin,K,C,140,3,2,220,3.0,21,7,130,FDA_25,3,1.33,0.67,40.692320
50,Nutri-grain Wheat,K,C,90,3,0,170,3.0,18,2,90,FDA_25,3,1.00,1.00,59.642837
51,Oatmeal Raisin Crisp,G,C,130,3,2,170,1.5,13.5,10,120,FDA_25,3,1.25,0.50,30.450843
52,Post Nat. Raisin Bran,P,C,120,3,1,200,6.0,11,14,260,FDA_25,3,1.33,0.67,37.840594
53,Product 19,K,C,100,3,0,320,1.0,20,3,45,FDA_100,3,1.00,1.00,41.503540
54,Puffed Rice,Q,C,50,1,0,0,0.0,13,0,15,FDA_0,3,0.50,1.00,60.756112
55,Puffed Wheat,Q,C,50,2,0,0,1.0,10,0,50,FDA_0,3,0.50,1.00,63.005645
56,Quaker Oat Squares,Q,C,100,4,1,135,2.0,14,6,110,FDA_25,3,1.00,0.50,49.511874
57,Quaker Oatmeal,Q,H,100,5,2,0,2.7,--carbo--,--sugars--,110,FDA_0,1,1.00,0.67,50.828392
58,Raisin Bran,K,C,120,3,1,210,5.0,14,12,240,FDA_25,2,1.33,0.75,39.259197
59,Raisin Nut Bran,G,C,100,3,2,140,2.5,10.5,8,140,FDA_25,3,1.00,0.50,39.703400
60,Raisin Squares,K,C,90,2,0,0,2.0,15,6,110,FDA_25,3,1.00,0.50,55.333142
61,Rice Chex,R,C,110,1,0,240,0.0,23,2,30,FDA_25,1,1.00,1.13,41.998933
62,Rice Krispies,K,C,110,2,0,290,0.0,22,3,35,FDA_25,1,1.00,1.00,40.560159
63,Shredded Wheat,N,C,80,2,0,0,3.0,16,0,95,FDA_0,1,0.83,1.00,68.235885
64,Shredded Wheat 'n'Bran,N,C,90,3,0,0,4.0,19,0,140,FDA_0,1,1.00,0.67,74.472949
65,Shredded Wheat spoon size,N,C,90,3,0,0,3.0,20,0,120,FDA_0,1,1.00,0.67,72.801787
66,Smacks,K,C,110,2,1,70,1.0,9,15,40,FDA_25,2,1.00,0.75,31.230054
67,Special K,K,C,110,6,0,230,1.0,16,3,55,FDA_25,1,1.00,1.00,53.131324
68,Strawberry Fruit Wheats,N,C,90,2,0,15,3.0,15,5,90,FDA_25,2,1.00,1.00,59.363993
69,Total Corn Flakes,G,C,110,2,1,200,0.0,21,3,35,FDA_100,3,1.00,1.00,38.839746
70,Total Raisin Bran,G,C,140,3,1,190,4.0,15,14,230,FDA_100,3,1.50,1.00,28.592785
71,Total Whole Grain,G,C,100,3,1,200,3.0,16,3,110,FDA_100,3,1.00,1.00,46.658844
72,Triples,G,C,110,2,1,250,0.0,21,3,60,FDA_25,3,1.00,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13,12,25,FDA_25,2,1.00,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17,3,115,FDA_25,1,1.00,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17,3,110,FDA_25,1,1.00,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16,8,60,FDA_25,1,1.00,0.75,36.187559

In [64]:
df_cereal.mean()

calories    106.883117
protein       2.545455
fat           1.012987
sodium      159.675325
fiber         2.151948
carbo        14.802632
sugars        7.026316
potass       98.666667
shelf         2.207792
weight        1.029610
cups          0.821039
rating       42.665705
dtype: float64

In [65]:
df_cereal.fillna(df_cereal.mean(), inplace=True)

In [66]:
df_cereal.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.000000,FDA_25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.000000,FDA_0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.000000,FDA_25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.000000,FDA_25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,98.666667,FDA_25,3,1.0,0.75,34.384843